#!/bin/sh

## All hail the MIT License
# Heavily based on
# https://gitlab.com/fedora/sigs/sway/sway-config-fedora/-/blob/fedora/sway/start-sway

## Internal variables
SWAY_EXTRA_ARGS=""

## General exports
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export MOZ_ENABLE_WAYLAND=1
export MOZ_USE_XINPUT2=1

## Hardware compatibility
# We can't be sure that the virtual GPU is compatible with Sway.
# We should be attempting to detect an EGL driver instead, but that appears
# to be a bit more complicated.
case $(systemd-detect-virt --vm) in
"none" | "") ;;
"kvm")
	# https://github.com/swaywm/sway/issues/6581
	export WLR_NO_HARDWARE_CURSORS=1
	# There's two drivers we can get here, depending on the 3D acceleration
	# flag state: either virtio_gpu/virgl or kms_swrast/llvmpipe.
	#
	# The former one causes graphical glitches in OpenGL apps when using
	# 'pixman' renderer. The latter will crash 'gles2' renderer outright.
	# Neither of those support 'vulkan'.
	#
	# The choice is obvious, at least until we learn to detect the driver
	# instead of abusing the virtualization technology identifier.
	#
	# See also: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/2871
	export WLR_RENDERER=pixman
	;;
*)
	# https://github.com/swaywm/sway/issues/6581
	export WLR_NO_HARDWARE_CURSORS=1
	;;
esac

## Nvidia workaround
# https://github.com/crispyricepc/sway-nvidia
if [ -f /proc/driver/nvidia/version ]; then
	export WLR_NO_HARDWARE_CURSORS=1
	export WLR_RENDERER=vulkan
	export QT_QPA_PLATFORM=wayland
	export GBM_BACKEND=nvidia-drm
	export __GL_GSYNC_ALLOWED=0
	export __GL_VRR_ALLOWED=0
	export __GLX_VENDOR_LIBRARY_NAME=nvidia
	export XWAYLAND_NO_GLAMOR=1

	SWAY_EXTRA_ARGS="$SWAY_EXTRA_ARGS --unsupported-gpu"
fi

## Load system environment customizations
if [ -f /etc/sway/environment ]; then
	set -o allexport
	# shellcheck source=/dev/null
	. /etc/sway/environment
	set +o allexport
fi

## Load user environment customizations
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/sway/environment" ]; then
	set -o allexport
	# shellcheck source=/dev/null
	. "${XDG_CONFIG_HOME:-$HOME/.config}/sway/environment"
	set +o allexport
fi

## Unexport internal variables
# export -n is not POSIX :(
_SWAY_EXTRA_ARGS="$SWAY_EXTRA_ARGS"
unset SWAY_EXTRA_ARGS

# Start sway with extra arguments and send output to the journal
# shellcheck disable=SC2086 # quoted expansion of EXTRA_ARGS can produce empty field
exec systemd-cat -- /usr/bin/sway $_SWAY_EXTRA_ARGS "$@"
